apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: artifactory-oss-nginx
  namespace: artifactory-oss
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`artifactory.gpu02.lysdemolab.fr`)
    middlewares:
#    - name: security
#    - name: ratelimit
    services:
    - name: artifactory-oss-artifactory-nginx
      port: 80
  tls:
    certResolver: letsencrypt
